// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository_Test.ApplicationDbContext;

namespace Repository_Test.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Repository_Test.Areas.Employees.Data.Entity.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("employeeCode");

                    b.Property<string>("employeeDesignation");

                    b.Property<string>("employeeName");

                    b.Property<string>("employeeSalary");

                    b.HasKey("Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("Repository_Test.Areas.Inventory.Data.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("productCode");

                    b.Property<string>("productName");

                    b.HasKey("Id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Repository_Test.Areas.Inventory.Data.Entity.SalesInvoiceDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Price");

                    b.Property<int?>("Quantity");

                    b.Property<int?>("productId");

                    b.Property<int?>("salesInvoiceMasterId");

                    b.HasKey("Id");

                    b.HasIndex("productId");

                    b.HasIndex("salesInvoiceMasterId");

                    b.ToTable("salesInvoiceDetails");
                });

            modelBuilder.Entity("Repository_Test.Areas.Inventory.Data.Entity.SalesInvoiceMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Price");

                    b.Property<int?>("Quantity");

                    b.HasKey("Id");

                    b.ToTable("salesInvoiceMasters");
                });

            modelBuilder.Entity("Repository_Test.Areas.Inventory.Data.Entity.SalesInvoiceDetails", b =>
                {
                    b.HasOne("Repository_Test.Areas.Inventory.Data.Entity.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("Repository_Test.Areas.Inventory.Data.Entity.SalesInvoiceMaster", "salesInvoiceMaster")
                        .WithMany()
                        .HasForeignKey("salesInvoiceMasterId");
                });
#pragma warning restore 612, 618
        }
    }
}
